# pubspec.yaml
name: task_manager
description: A task management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  google_fonts: ^6.1.0
  loading_animation_widget: ^1.2.0+4
  animate_do: ^3.3.4
  lucide_icons: ^0.257.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true